name: Dev Build

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: chmod +x gradlew

      - name: Build
        run: ./gradlew build -Pcommit=${{ github.sha }}


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: Artifacts
            path: build/libs/
